const recipes = [
  {
    id: 1,
    title: "Avocado Toast with Poached Egg",
    tags: ["breakfast", "quick", "healthy", "vegetarian", "15min"],
    prepTime: 10,
    cookTime: 8,
    totalTime: 18,
    difficulty: "Easy",
    category: "breakfast",
    description: "A classic brunch favorite featuring creamy avocado and perfectly poached eggs on crispy sourdough toast with a hint of red pepper flakes.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
    ingredients: [
      "2 slices sourdough bread",
      "1 ripe avocado",
      "2 large eggs",
      "1 tbsp white vinegar",
      "Red pepper flakes",
      "Salt and pepper to taste",
      "Fresh lemon juice",
      "Extra virgin olive oil"
    ],
    instructions: [
      "Toast the sourdough bread until golden and crispy",
      "Slice avocado in half, remove pit, and scoop out flesh into a bowl",
      "Mash avocado with fork, add lemon juice, salt, and pepper",
      "Bring a pot of water to a gentle simmer, add vinegar",
      "Create a gentle whirlpool, gently drop eggs into the center",
      "Cook for 3 minutes for runny yolk or 4 minutes for firm",
      "Spread mashed avocado generously on toast",
      "Top with poached eggs, drizzle with olive oil, sprinkle with red pepper flakes"
    ],
    tip: "Add a sprinkle of everything bagel seasoning for extra flavor!",
    servings: 1,
    calories: 450,
    protein: "18g",
    carbs: "35g",
    fat: "28g",
    cuisine: "American",
    rating: 4.8,
    ratingCount: 320,
    videoUrl: "",
    allergens: ["eggs", "gluten"],
    dietaryInfo: ["vegetarian", "healthy"]
  },
  {
    id: 2,
    title: "Fluffy Blueberry Pancakes",
    tags: ["breakfast", "dessert", "15min", "homemade"],
    prepTime: 15,
    cookTime: 10,
    totalTime: 25,
    difficulty: "Easy",
    category: "breakfast",
    description: "Light and fluffy pancakes bursting with fresh blueberries, served with butter and maple syrup.",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800",
    ingredients: [
      "1 cup all-purpose flour",
      "2 tbsp granulated sugar",
      "2 tsp baking powder",
      "1 tsp baking soda",
      "1/2 tsp salt",
      "1 1/4 cups buttermilk",
      "1 large egg",
      "3 tbsp melted butter",
      "1 1/2 cups fresh blueberries"
    ],
    instructions: [
      "In a large bowl, whisk together flour, sugar, baking powder, baking soda, and salt",
      "In another bowl, combine buttermilk, egg, and melted butter",
      "Pour wet ingredients into dry and mix just until combined (don't overmix!)",
      "Gently fold in blueberries",
      "Heat a non-stick pan or griddle over medium heat",
      "Pour 1/4 cup batter per pancake for 4-inch pancakes",
      "Cook until bubbles form on surface (about 2 minutes)",
      "Flip carefully and cook another 1-2 minutes until golden",
      "Serve immediately with warm syrup and butter"
    ],
    tip: "For extra fluffy pancakes, let the batter rest for 10 minutes before cooking!",
    servings: 2,
    calories: 520,
    protein: "12g",
    carbs: "80g",
    fat: "18g",
    cuisine: "American",
    rating: 4.9,
    ratingCount: 450,
    videoUrl: "",
    allergens: ["eggs", "gluten", "dairy"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 3,
    title: "Classic Avocado Cobb Salad",
    tags: ["healthy", "lunch", "vegetarian", "main"],
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    difficulty: "Medium",
    category: "soup-salad",
    description: "A vibrant, protein-packed salad with creamy avocado, crisp greens, and creamy dressing.",
    image: "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800",
    ingredients: [
      "2 cups mixed greens",
      "1 ripe avocado, sliced",
      "1 cup cherry tomatoes, halved",
      "1/2 cup crumbled feta cheese",
      "1/4 cup blueberries (for sweetness)",
      "Hard-boiled eggs (2-3, sliced)",
      "Balsamic glaze",
      "Olive oil and lemon juice",
      "Salt, pepper, and red pepper flakes"
    ],
    instructions: [
      "Wash and dry mixed greens thoroughly",
      "Arrange greens on a large serving plate",
      "Top with avocado slices, cherry tomatoes, and diced hard-boiled eggs",
      "Crumble feta cheese over the top",
      "Gently toss the blueberries on one side for color contrast",
      "In a small bowl, whisk together olive oil, lemon juice, salt, and pepper",
      "Drizzle dressing over salad",
      "Finish with balsamic glaze and red pepper flakes"
    ],
    tip: "Use a rolling pin to gently crush blueberries to release their flavor!",
    servings: 2,
    calories: 410,
    protein: "14g",
    carbs: "20g",
    fat: "32g",
    cuisine: "American",
    rating: 4.7,
    ratingCount: 215,
    videoUrl: "",
    allergens: ["eggs", "dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 4,
    title: "Vegetable Stir Fry",
    tags: ["quick", "healthy", "main", "15min", "vegetarian"],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    difficulty: "Easy",
    category: "main",
    description: "Bright, colorful stir-fried vegetables in a savory sesame-ginger sauce.",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800",
    ingredients: [
      "2 cups mixed vegetables (broccoli, bell peppers, carrot)",
      "1 cup snap peas",
      "2 cloves garlic, minced",
      "1 tbsp fresh ginger, grated",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "1 tbsp cornstarch",
      "1 tbsp vegetable oil",
      "Green onions for garnish"
    ],
    instructions: [
      "Measure and prep all vegetables - cut into bite-sized pieces",
      "Mix soy sauce, sesame oil, cornstarch, and 3 tbsp water in a bowl",
      "Heat wok or large skillet over high heat",
      "Add vegetable oil and stir-fry vegetables for 4-5 minutes",
      "Add ginger and garlic, cook for 30 seconds until fragrant",
      "Pour sauce over vegetables and toss to coat",
      "Continue cooking for 2-3 minutes until sauce thickens",
      "Garnish with green onions and serve over cooked rice"
    ],
    tip: "Keep your cooking surface hot! Preheat the wok with oil before adding vegetables.",
    servings: 2,
    calories: 280,
    protein: "6g",
    carbs: "30g",
    fat: "16g",
    cuisine: "Asian",
    rating: 4.6,
    ratingCount: 180,
    videoUrl: "",
    allergens: ["soy"],
    dietaryInfo: ["vegan", "vegetarian", "dairy-free"]
  },
  {
    id: 5,
    title: "Creamy Mushroom Risotto",
    tags: ["dinner", "main", "slower", "medium"],
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "Medium",
    category: "main",
    description: "Rich, creamy Italian rice dish with earthy mushrooms and parmesan cheese.",
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
    ingredients: [
      "1 1/2 cups arborio rice",
      "2 cups vegetable broth, warm",
      "8 oz mushrooms, sliced",
      "1 small onion, diced",
      "2 cloves garlic, minced",
      "1/2 cup white wine",
      "1/4 cup parmesan cheese",
      "2 tbsp butter",
      "Fresh thyme and parsley"
    ],
    instructions: [
      "Heat broth in a saucepan and keep it warm",
      "In a large pan, sauté mushrooms until golden, remove and set aside",
      "Add butter and onion, cook until translucent",
      "Add garlic and cook for 30 seconds",
      "Add rice and toast for 2 minutes, stirring constantly",
      "Pour in white wine and stir until absorbed",
      "Add warm broth one ladle at a time, stirring frequently",
      "Continue for 20-25 minutes until rice is creamy and al dente",
      "Stir in cheese, mushrooms, and seasonings",
      "Let rest 2 minutes before serving"
    ],
    tip: "Use warm broth - adding cold broth will slow down the cooking process!",
    servings: 4,
    calories: 420,
    protein: "10g",
    carbs: "65g",
    fat: "12g",
    cuisine: "Italian",
    rating: 4.8,
    ratingCount: 310,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 6,
    title: "Spaghetti Carbonara",
    tags: ["italian", "main", "30min", "dinner"],
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "Medium",
    category: "main",
    description: "Authentic Roman pasta with crispy pancetta, egg yolk, and pecorino cheese.",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800",
    ingredients: [
      "400g spaghetti",
      "200g pancetta or guanciale",
      "4 egg yolks",
      "1 cup pecorino romano, grated",
      "Freshly ground black pepper",
      "2 cloves garlic"
    ],
    instructions: [
      "Boil spaghetti in salted water until al dente, reserve 1/2 cup pasta water",
      "In a large pan, cook pancetta until crispy",
      "While pasta cooks, whisk together egg yolks, pecorino, and pepper",
      "Sauté garlic in pancetta fat until fragrant (optional)",
      "Chop pancetta and set aside",
      "Drain pasta, return to hot pan",
      "Remove pan from heat - this is crucial!",
      "Add pasta to egg mixture (in separate bowl) and toss quickly",
      "Add pancetta and toss vigorously",
      "Add pasta water as needed for creamy consistency"
    ],
    tip: "The key is keeping the pan off heat while combining eggs and pasta!",
    servings: 4,
    calories: 650,
    protein: "25g",
    carbs: "75g",
    fat: "28g",
    cuisine: "Italian",
    rating: 4.9,
    ratingCount: 500,
    videoUrl: "",
    allergens: ["eggs", "dairy", "gluten"],
    dietaryInfo: []
  },
  {
    id: 7,
    title: "Homemade Pizza Margherita",
    tags: ["dinner", "30min", "homemade", "main"],
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    difficulty: "Medium",
    category: "main",
    description: "Classic Neapolitan-style pizza with San Marzano tomatoes, fresh mozzarella, and basil.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    ingredients: [
      "500g pizza dough",
      "2 cups San Marzano tomato sauce",
      "8 oz fresh mozzarella, sliced",
      "Fresh basil leaves",
      "Extra virgin olive oil",
      "Flaky sea salt",
      "Garlic cloves, thinly sliced"
    ],
    instructions: [
      "Preheat oven to maximum temperature (or preheat pizza stone)",
      "Stretch pizza dough into a 12-inch round on a floured surface",
      "Transfer dough to a pizza peel or baking sheet lined with parchment",
      "Spread tomato sauce evenly, leaving a 1-inch border",
      "Arrange mozzarella slices on top",
      "Drizzle with olive oil and top with sliced garlic",
      "Bake at 500°F (250°C) for 10-12 minutes until crust is charred",
      "During last 2 minutes, add fresh basil leaves",
      "Garnish with sea salt and serve immediately"
    ],
    tip: "Use a pizza stone if you have one - it gives the authentic crust texture!",
    servings: 2,
    calories: 780,
    protein: "28g",
    carbs: "95g",
    fat: "28g",
    cuisine: "Italian",
    rating: 4.8,
    ratingCount: 390,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 8,
    title: "Grilled Chicken Breast",
    tags: ["dinner", "healthy", "30min", "main"],
    prepTime: 15,
    cookTime: 12,
    totalTime: 27,
    difficulty: "Easy",
    category: "main",
    description: "Perfectly seasoned grilled chicken with crispy skin and juicy interior.",
    image: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800",
    ingredients: [
      "2 boneless chicken breasts",
      "2 tbsp olive oil",
      "2 tsp garlic powder",
      "1 tsp smoked paprika",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
      "Fresh lemon wedges"
    ],
    instructions: [
      "Pat chicken breasts completely dry with paper towels",
      "In a small bowl, mix olive oil with all seasonings",
      "Place chicken in a dish, pour marinade over and coat evenly",
      "Let marinate for at least 15 minutes (or up to 2 hours)",
      "Preheat grill for medium-high heat",
      "Grill chicken for 6-7 minutes per side",
      "Check internal temperature reaches 165°F (74°C)",
      "Rest chicken for 5 minutes before slicing",
      "Serve with lemon wedges"
    ],
    tip: "Don't flip the chicken too often - patience leads to perfect grill marks!",
    servings: 2,
    calories: 290,
    protein: "45g",
    carbs: "2g",
    fat: "14g",
    cuisine: "American",
    rating: 4.6,
    ratingCount: 220,
    videoUrl: "",
    allergens: [],
    dietaryInfo: ["gluten-free", "dairy-free", "low-carb"]
  },
  {
    id: 9,
    title: "Thai Green Curry",
    tags: ["asian", "dinner", "45min", "spicy"],
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "Medium",
    category: "main",
    description: "Aromatic Thai dish with green curry paste, coconut milk, and your choice of protein.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
    ingredients: [
      "2 cans coconut milk",
      "3 tbsp green curry paste",
      "500g chicken or tofu",
      "1 bell pepper, sliced",
      "1 cup bamboo shoots",
      "Thai basil leaves",
      "Fish sauce and palm sugar",
      "Jasmine rice for serving"
    ],
    instructions: [
      "Split coconut milk - reserve 1/4 cup of thick cream, whisk min with remaining",
      "Heat a wok over medium-high heat, add 2 tbsp coconut cream",
      "Stir in curry paste, cook until fragrant (2-3 minutes)",
      "Add protein and brown on all sides",
      "Pour in remaining coconut milk, bring to a simmer",
      "Add vegetables, fish sauce, and palm sugar to taste",
      "Simmer for 15-20 minutes until chicken is cooked through",
      "Stir in Thai basil in last minute",
      "Serve over jasmine rice"
    ],
    tip: "Adjust spice level by adding more or less green curry paste!",
    servings: 4,
    calories: 550,
    protein: "32g",
    carbs: "45g",
    fat: "30g",
    cuisine: "Thai",
    rating: 4.7,
    ratingCount: 340,
    videoUrl: "",
    allergens: ["fish", "coconut"],
    dietaryInfo: ["dairy-free", "gluten-free"]
  },
  {
    id: 10,
    title: "Chocolate Lava Cake",
    tags: ["dessert", "30min", "baking", "special"],
    prepTime: 20,
    cookTime: 14,
    totalTime: 34,
    difficulty: "Medium",
    category: "dessert",
    description: "Decadent chocolate cake with a molten center - pure chocolate heaven!",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800",
    ingredients: [
      "4 oz dark chocolate",
      "1/2 cup butter",
      "2 eggs + 2 egg yolks",
      "1/2 cup sugar",
      "2 tbsp all-purpose flour",
      "Pinch of salt",
      "Powdered sugar for dusting",
      "Vanilla ice cream for serving"
    ],
    instructions: [
      "Preheat oven to 425°F (220°C). Grease 4 ramekins",
      "Melt chocolate and butter together in microwave or double boiler",
      "Whisk in eggs, yolks, and sugar until smooth",
      "Sift in flour and mix gently until combined",
      "Divide batter evenly among prepared ramekins",
      "Bake for 12-14 minutes until edges are set but center is soft",
      "Let cool for 1 minute, then invert onto plates",
      "Dust with powdered sugar",
      "Serve immediately with ice cream"
    ],
    tip: "The key is not to overbake - remove when edges are set but center still wobbly!",
    servings: 4,
    calories: 480,
    protein: "6g",
    carbs: "42g",
    fat: "34g",
    cuisine: "French",
    rating: 4.9,
    ratingCount: 420,
    videoUrl: "",
    allergens: ["dairy", "eggs", "gluten", "soy"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 11,
    title: "Classic Lemon Blueberry Muffins",
    tags: ["breakfast", "dessert", "45min", "baking"],
    prepTime: 20,
    cookTime: 22,
    totalTime: 42,
    difficulty: "Medium",
    category: "breakfast",
    description: "Tangy lemon muffins bursting with sweet blueberries and topped with lemon glaze.",
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800",
    ingredients: [
      "2 cups all-purpose flour",
      "1 cup sugar",
      "2 tsp baking powder",
      "1/2 tsp baking soda",
      "1/4 tsp salt",
      "Zest of 1 lemon",
      "1/2 cup milk",
      "1/2 cup melted butter",
      "1 large egg",
      "1 tbsp lemon juice",
      "1 cup blueberries",
      "Lemon glaze"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C). Line muffin tin with paper cups",
      "Whisk flour, sugar, baking powder, baking soda, and salt",
      "Add lemon zest and mix",
      "In separate bowl, combine milk, butter, egg, and lemon juice",
      "Pour wet ingredients into dry, mix until just combined",
      "Gently fold in blueberries",
      "Fill muffin cups 3/4 full",
      "Bake for 20-22 minutes until golden",
      "Cool in pan for 5 minutes, then on wire rack",
      "Drizzle with lemon glaze and let set"
    ],
    tip: "Don't overmix or the muffins will be tough - mix until batter is just combined!",
    servings: 12,
    calories: 240,
    protein: "3g",
    carbs: "38g",
    fat: "9g",
    cuisine: "American",
    rating: 4.7,
    ratingCount: 290,
    videoUrl: "",
    allergens: ["dairy", "eggs", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 12,
    title: "Greek Salad",
    tags: ["healthy", "lunch", "vegetarian", "main", "15min"],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "Easy",
    category: "soup-salad",
    description: "Fresh Mediterranean salad with crisp vegetables, tangy feta, and kalamata olives.",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800",
    ingredients: [
      "2 large tomatoes, sliced",
      "1 cucumber, chunked",
      "1 red onion, sliced",
      "1 cup cherry tomatoes",
      "200g feta cheese, cubed",
      "1/2 cup kalamata olives",
      "Extra virgin olive oil",
      "Red wine vinegar",
      "Oregano and dried mint"
    ],
    instructions: [
      "Cut all vegetables into large, rustic pieces",
      "Arrange vegetables on a large serving platter",
      "Arrange feta cubes on top",
      "Add olives around the edges",
      "Drizzle generously with olive oil",
      "Sprinkle with oregano and dried mint",
      "Finish with a splash of red wine vinegar",
      "Salt and pepper to taste",
      "Toss gently just before serving"
    ],
    tip: "Use a pinch of dried mint for an authentic Greek touch!",
    servings: 4,
    calories: 320,
    protein: "8g",
    carbs: "14g",
    fat: "28g",
    cuisine: "Greek",
    rating: 4.8,
    ratingCount: 150,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free", "low-carb"]
  },
  {
    id: 13,
    title: "Beef Tacos",
    tags: ["dinner", "15min", "comfort", "main"],
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    difficulty: "Easy",
    category: "main",
    description: "Easy weeknight dinner with seasoned ground beef and all the fresh taco toppings.",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800",
    ingredients: [
      "1 lb ground beef",
      "1 packet taco seasoning",
      "6-8 small corn tortillas",
      "Lettuce, diced",
      "Cheddar cheese, shredded",
      "Diced tomatoes",
      "Sour cream",
      "Salsa",
      "Fresh cilantro"
    ],
    instructions: [
      "Brown beef in a large skillet over medium-high heat, breaking up as it cooks",
      "Drain excess fat",
      "Add taco seasoning and 1/2 cup water, simmer for 5 minutes",
      "Warm tortillas in a dry skillet or directly over flame",
      "Take tortillas and warm water (30-60 seconds) to make them pliable",
      "Assemble plates with tortillas and all toppings",
      "Spoon seasoned beef into center",
      "Top with cheese, lettuce, tomatoes, and sour cream",
      "Add fresh salsa and cilantro"
    ],
    tip: "Warm tortillas directly over a gas burner for those perfect char marks!",
    servings: 4,
    calories: 450,
    protein: "26g",
    carbs: "32g",
    fat: "24g",
    cuisine: "Mexican",
    rating: 4.6,
    ratingCount: 310,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["gluten-free"]
  },
  {
    id: 14,
    title: "Fresh Strawberry Smoothie",
    tags: ["drink", "breakfast", "quick", "healthy"],
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "Easy",
    category: "drinks",
    description: "Refreshingly sweet and nutritious smoothie made with fresh strawberries and bananas.",
    image: "https://images.unsplash.com/photo-1553530666-ba11a9064628?w=800",
    ingredients: [
      "2 cups fresh strawberries",
      "1 ripe banana",
      "1/2 cup Greek yogurt",
      "1 cup milk of choice",
      "1 tbsp honey or maple syrup",
      "1/2 cup ice"
    ],
    instructions: [
      "Add all ingredients to a blender",
      "Blend on high until completely smooth",
      "Taste and add more sweetener if desired",
      "If too thick, add more milk",
      "If too thin, add more ice",
      "Pour into glasses and serve immediately",
      "Garnish with a fresh strawberry if desired"
    ],
    tip: "Freeze extra bananas beforehand for even creamier smoothies year-round!",
    servings: 2,
    calories: 180,
    protein: "6g",
    carbs: "36g",
    fat: "2g",
    cuisine: "American",
    rating: 4.8,
    ratingCount: 120,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 15,
    title: "Warm Apple Crisp",
    tags: ["dessert", "45min", "baking", "comfort"],
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "Easy",
    category: "dessert",
    description: "Easy baked apple dessert with spiced apples and crispy oat topping.",
    image: "https://images.unsplash.com/photo-1488477181946-6428a029177b?w=800",
    ingredients: [
      "6 medium apples, sliced",
      "2 tbsp lemon juice",
      "3/4 cup sugar",
      "1 tsp cinnamon",
      "1/4 tsp nutmeg",
      "For topping: 3/4 cup oats, 3/4 cup flour, 1/2 cup sugar, 1/2 cup butter, 1 tsp cinnamon",
      "Vanilla ice cream for serving"
    ],
    instructions: [
      "Preheat oven to 350°F (175°C)",
      "Toss sliced apples with lemon juice, sugar, cinnamon, and nutmeg",
      "Transfer to a 9x9 baking dish",
      "Mix topping ingredients: oats, flour, sugar, butter, and cinnamon",
      "Crumble butter into the dry mix with fingers",
      "Sprinkle topping evenly over apples",
      "Bake for 35-40 minutes until bubbly and golden",
      "Let cool 10 minutes, serve warm with vanilla ice cream"
    ],
    tip: "Use a mix of Granny Smith and Honeycrisp apples for the best flavor!",
    servings: 6,
    calories: 380,
    protein: "3g",
    carbs: "65g",
    fat: "14g",
    cuisine: "American",
    rating: 4.7,
    ratingCount: 260,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 16,
    title: "Chicken Noodle Soup",
    tags: ["healthy", "dinner", "slower", "comfort"],
    prepTime: 20,
    cookTime: 40,
    totalTime: 60,
    difficulty: "Easy",
    category: "main",
    description: "Classic comforting soup with tender chicken, vegetables, and fresh egg noodles.",
    image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
    ingredients: [
      "1 lb boneless chicken breasts",
      "1 onion, diced",
      "2 carrots, sliced",
      "2 celery stalks, sliced",
      "6 cups chicken broth",
      "2 cups egg noodles",
      "3 cloves garlic, minced",
      "Fresh parsley and thyme",
      "Salt and pepper"
    ],
    instructions: [
      "Combine broth, carrots, celery, and onion in large pot",
      "Bring to a boil, then simmer for 10 minutes",
      "Add chicken and garlic, simmer until chicken is cooked through (20-25 minutes)",
      "Remove chicken and dice when cool",
      "Add noodles to broth, cook for 6-8 minutes",
      "Return diced chicken to pot, season with salt and pepper",
      "Simmer for an additional 2 minutes",
      "Garnish with fresh parsley and thyme"
    ],
    tip: "Let soup cool slightly before serving - the flavor develops as it sits!",
    servings: 4,
    calories: 310,
    protein: "30g",
    carbs: "28g",
    fat: "7g",
    cuisine: "American",
    rating: 4.8,
    ratingCount: 380,
    videoUrl: "",
    allergens: ["gluten", "eggs"],
    dietaryInfo: ["dairy-free"]
  },
  {
    id: 17,
    title: "Vietnamese Pho",
    tags: ["asian", "slower", "dinner", "main"],
    prepTime: 30,
    cookTime: 60,
    totalTime: 90,
    difficulty: "Medium",
    category: "main",
    description: "Authentic Vietnamese beef noodle soup with aromatic star anise broth.",
    image: "https://images.unsplash.com/photo-1603506245530-842b27872d75?w=800",
    ingredients: [
      "1 lb beef short ribs or sirloin",
      "1 cinnamon stick",
      "3 star anise",
      "3 cloves garlic",
      "1 inch ginger",
      "2 onions",
      "1 bunch rice noodles",
      "4 cups beef broth",
      "Fresh herbs: basil, cilantro, mint",
      "Bean sprouts and lime wedges"
    ],
    instructions: [
      "Roast onions, ginger, and garlic until blackened",
      "Place in a pot with spices, broth, and tomatoes (optional)",
      "Add water and bring to a boil, then simmer for 1 hour",
      "Add beef, simmer until very tender (1-2 hours more)",
      "Strain broth, season with fish sauce and sugar",
      "Meanwhile, soak rice noodles according to package",
      "Slice beef thinly for bibimbap style",
      "Build bowls: noodles, soft beef slices, hot broth, herbs, sprouts, and lime"
    ],
    tip: "Add raw beef slices right into serving bowls for a fresher bowl!",
    servings: 4,
    calories: 450,
    protein: "35g",
    carbs: "50g",
    fat: "12g",
    cuisine: "Vietnamese",
    rating: 4.9,
    ratingCount: 410,
    videoUrl: "",
    allergens: ["fish"],
    dietaryInfo: ["dairy-free", "gluten-free"]
  },
  {
    id: 18,
    title: "Mango Sticky Rice",
    tags: ["dessert", "asian", "slower", "special"],
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    difficulty: "Medium",
    category: "dessert",
    description: "Beloved Thai dessert with sweet coconut milk and fragrant jasmine rice.",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800",
    ingredients: [
      "1 cup sticky rice, soaked in water for 2 hours",
      "1 can coconut milk",
      "1/2 cup sugar",
      "1/4 tsp salt",
      "A few pandan leaves (optional)",
      "1 ripe mango, sliced",
      "Mung bean or sesem seed for serving"
    ],
    instructions: [
      "Drain soaked rice and place in a steamer basket lined with cheesecloth",
      "Add a few pandan leaves for fragrance",
      "Steam over high heat for 20-25 minutes until fluffy",
      "Combine coconut milk, sugar, and salt in a saucepan",
      "Stir over medium heat until sugar dissolves",
      "Bring to a boil, then reduce to low and simmer for 5 minutes",
      "Let coconut sauce cool to room temperature",
      "Serve sticky rice warm topped with mango and coconut milk sauce"
    ],
    tip: "Soak rice the night before for best texture!",
    servings: 4,
    calories: 380,
    protein: "4g",
    carbs: "68g",
    fat: "12g",
    cuisine: "Thai",
    rating: 4.8,
    ratingCount: 270,
    videoUrl: "",
    allergens: ["coconut"],
    dietaryInfo: ["vegan", "vegetarian", "dairy-free", "gluten-free"]
  },
  {
    id: 19,
    title: "Classic Caesar Salad",
    tags: ["healthy", "lunch", "main", "30min"],
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    difficulty: "Easy",
    category: "soup-salad",
    description: "Crisp romaine lettuce with homemade Caesar dressing and crispy croutons.",
    image: "https://images.unsplash.com/photo-1514812535759-f346c6b0d9d9?w=800",
    ingredients: [
      "2 heads romaine lettuce",
      "1 cup homemade Caesar dressing",
      "1/2 cup parmesan cheese, shaved",
      "1 cup croutons",
      "Anchovies (optional)",
      "Black pepper"
    ],
    instructions: [
      "Remove outer leaves from romaine, wash and dry thoroughly",
      "Cut lettuce crosswise into 1/4 inch strips",
      "Place lettuce in a large bowl",
      "Add dressing and toss, adding 1 tablespoon at a time",
      "Top with parmesan shavings, croutons",
      "Add anchovies if desired, freshly ground pepper",
      "Toss gently to combine",
      "Serve immediately while croutons are crispy"
    ],
    tip: "Room temperature dressing makes a silkier sauce!",
    servings: 2,
    calories: 340,
    protein: "12g",
    carbs: "18g",
    fat: "25g",
    cuisine: "Italian",
    rating: 4.6,
    ratingCount: 190,
    videoUrl: "",
    allergens: ["dairy", "gluten", "fish", "eggs"],
    dietaryInfo: []
  },
  {
    id: 20,
    title: "Tom Yum Soup",
    tags: ["asian", "spicy", "soup", "healthy"],
    prepTime: 20,
    cookTime: 30,
    totalTime: 50,
    difficulty: "Medium",
    category: "main",
    description: "Hot and sour Thai soup with lemongrass, galangal, and fresh lime.",
    image: "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800",
    ingredients: [
      "4 cups chicken broth",
      "2 lemongrass stalks",
      "2 kaffir lime leaves",
      "2 slices galangal or fresh ginger",
      "2 tbsp shrimp paste (optional)",
      "3 tbsp fish sauce",
      "2 tbsp lime juice",
      "2 tbsp palm sugar",
      "Thai chilies, mushrooms, shrimp or chicken"
    ],
    instructions: [
      "Toast seasonings in 1/2 cup broth for 2 minutes",
      "Add remaining broth and bring to a boil",
      "Add fish sauce, lime juice, and sugar, stirring until dissolved",
      "Add protein and vegetables simmer for 5 minutes",
      "Remove whole lemongrass stalks",
      "Stir in lime juice and fresh chilies",
      "Season to taste, garnish with cilantro",
      "Serve hot with jasmine rice"
    ],
    tip: "Taste before serving - adjust fish sauce for saltiness and lime for acidity!",
    servings: 4,
    calories: 220,
    protein: "22g",
    carbs: "12g",
    fat: "8g",
    cuisine: "Thai",
    rating: 4.7,
    ratingCount: 230,
    videoUrl: "",
    allergens: ["fish", "shellfish"],
    dietaryInfo: ["dairy-free", "gluten-free"]
  },
  {
    id: 21,
    title: "Power Green Smoothie Bowl",
    tags: ["drink", "breakfast", "healthy", "15min"],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "Easy",
    category: "drinks",
    description: "Thick, creamy smoothie bowl packed with spinach, banana, and topping options.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    ingredients: [
      "2 cups packed spinach",
      "1 frozen banana",
      "1/2 cup almond milk",
      "1/2 cup Greek yogurt",
      "1 tbsp honey",
      "Toppings: granola, berries, chia seeds",
      "Coconut flakes"
    ],
    instructions: [
      "Add spinach, banana, yogurt, and milk to blender",
      "Blend on high until completely smooth",
      "Pour into a bowl - the result should be thick like soft serve ice cream",
      "Add honey to taste",
      "Top with desired toppings for texture and nutrition",
      "Add coconut flakes for extra flavor",
      "Serve immediately with a spoon"
    ],
    tip: "Freeze bananas beforehand for the creamiest smoothie bowl base!",
    servings: 1,
    calories: 310,
    protein: "14g",
    carbs: "52g",
    fat: "6g",
    cuisine: "American",
    rating: 4.9,
    ratingCount: 160,
    videoUrl: "",
    allergens: ["dairy", "tree nuts"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 22,
    title: "Santa Fe Chicken Quesadillas",
    tags: ["dinner", "15min", "comfort", "main"],
    prepTime: 10,
    cookTime: 10,
    totalTime: 20,
    difficulty: "Easy",
    category: "main",
    description: "Crispy quesadillas filled with seasoned chicken, peppers, and cheese.",
    image: "https://images.unsplash.com/photo-1544025162-d76690b67f11?w=800",
    ingredients: [
      "6 flour tortillas",
      "2 cups shredded chicken",
      "1 cup shredded OP pepper jack",
      "1/2 cup black beans",
      "Sliced bell peppers",
      "Green onions",
      "Sour cream and salsa for serving"
    ],
    instructions: [
      "Warm tortillas in a dry pan or directly over flame",
      "In each tortilla, add chicken, cheese, beans, and peppers",
      "Fold tortilla in half, press gently",
      "Place in a skillet over medium-high heat, cook 2-3 minutes per side",
      "Flip and continue cooking until cheese is melted and tortilla is crispy",
      "Remove from pan, cut into triangles",
      "Serve with salsa, sour cream, and green onions"
    ],
    tip: "Use the back of a spoon to press quesadillas while cooking for even melting!",
    servings: 3,
    calories: 520,
    protein: "35g",
    carbs: "42g",
    fat: "22g",
    cuisine: "Mexican",
    rating: 4.5,
    ratingCount: 200,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: []
  },
  {
    id: 23,
    title: "Homemade Chocolate Chip Cookies",
    tags: ["dessert", "30min", "baking", "comfort"],
    prepTime: 20,
    cookTime: 12,
    totalTime: 32,
    difficulty: "Easy",
    category: "dessert",
    description: "Classic chewy chocolate chip cookies straight from the oven.",
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800",
    ingredients: [
      "1 cup butter, softened",
      "3/4 cup brown sugar",
      "1/2 cup white sugar",
      "2 eggs",
      "2 tsp vanilla extract",
      "2 cups all-purpose flour",
      "1 tsp baking soda",
      "1 tsp salt",
      "2 cups chocolate chips"
    ],
    instructions: [
      "Preheat oven to 375°F (190°C), line baking sheet with parchment",
      "Cream butter and sugars until fluffy, about 3 minutes",
      "Add eggs and vanilla, mix well",
      "Mix in flour, baking soda, and salt",
      "Fold in chocolate chips (do not overmix)",
      "Scoop rounded tablespoons onto baking sheet",
      "Bake for 9-11 minutes until edges are golden",
      "Let cool on pan 2 minutes, then transfer to wire rack"
    ],
    tip: "Underbake slightly for chewier cookies - remove when edges just start to turn!",
    servings: 24,
    calories: 180,
    protein: "2g",
    carbs: "24g",
    fat: "9g",
    cuisine: "American",
    rating: 4.9,
    ratingCount: 480,
    videoUrl: "",
    allergens: ["dairy", "eggs", "gluten", "soy"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 24,
    title: "Berry Scones",
    tags: ["breakfast", "dessert", "30min", "baking"],
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    difficulty: "Medium",
    category: "breakfast",
    description: "Fluffy, buttery scones studded with blueberries and topped with cream.",
    image: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800",
    ingredients: [
      "1 3/4 cups all-purpose flour",
      "1/4 cup sugar",
      "2 tbsp baking powder",
      "1/2 tsp salt",
      "1/2 cup cold butter",
      "1 cup fresh blueberries",
      "1 cup heavy cream",
      "1 egg, beaten",
      "Coarse sugar for topping"
    ],
    instructions: [
      "Preheat oven to 400°F (200°C), line baking sheet",
      "Whisk flour, sugar, baking powder, and salt",
      "Cut in cold butter until mixture resembles coarse crumbs",
      "Gently fold in blueberries",
      "Add cream and egg mixture, stir just until combined",
      "Dough will be sticky - don't overwork",
      "Turn onto floured surface, pat into 1 inch thick circle",
      "Cut into 8 wedges, transfer to baking sheet",
      "Brush with cream, sprinkle with sugar, bake 20-22 minutes"
    ],
    tip: "Work quickly with cold ingredients for flaky, tender scones!",
    servings: 8,
    calories: 290,
    protein: "4g",
    carbs: "35g",
    fat: "16g",
    cuisine: "British",
    rating: 4.7,
    ratingCount: 140,
    videoUrl: "",
    allergens: ["dairy", "eggs", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 25,
    title: "Caprese sandwich",
    tags: ["lunch", "quick", "healthy", "vegetarian", "15min"],
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "Easy",
    category: "main",
    description: "Fresh Italian sandwich with mozzarella, tomatoes, basil, balsamic glaze.",
    image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800",
    ingredients: [
      "2 thick slices ciabatta or sourdough",
      "Fresh mozzarella slices",
      "4-5 ripe tomato slices",
      "Fresh basil leaves",
      "Balsamic glaze",
      "Extra virgin olive oil",
      "Salt and pepper"
    ],
    instructions: [
      "Brush one side of each bread slice with olive oil",
      "Place one slice bread-side down, season with salt and pepper",
      "Layer mozzarella, tomatoes, and basil",
      "Sprinkle balsamic glaze over tomatoes",
      "Add remaining cheese",
      "Top with second bread slice, olive oil-side up",
      "Grill sandwich in a pan until golden on both sides",
      "Cut in half diagonally, serve immediately"
    ],
    tip: "Add a drizzle of pesto for extra flavor!",
    servings: 1,
    calories: 420,
    protein: "18g",
    carbs: "45g",
    fat: "20g",
    cuisine: "Italian",
    rating: 4.8,
    ratingCount: 180,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 26,
    title: "Korean Beef Bulgogi",
    tags: ["dinner", "asian", "quick", "main"],
    prepTime: 20,
    cookTime: 10,
    totalTime: 30,
    difficulty: "Medium",
    category: "main",
    description: "Thinly sliced sweet and savory marinated beef stir-fried to perfection.",
    image: "https://images.unsplash.com/photo-1558985250-27a406d64cb3?w=800",
    ingredients: [
      "1 lb ribeye, thinly sliced",
      "1/4 cup soy sauce",
      "2 tbsp brown sugar",
      "1 tbsp sesame oil",
      "3 cloves garlic, minced",
      "1/2 Asian pear, grated",
      "1/2 onion, sliced",
      "Green onions and sesame seeds for garnish"
    ],
    instructions: [
      "Mix soy sauce, sugar, sesame oil, garlic, and pear in a bowl",
      "Add the sliced beef and onion, marinate for at least 30 minutes",
      "Heat a large skillet or wok over medium-high heat",
      "Cook the beef in batches to sear, not steam, about 2-3 minutes per batch",
      "Garnish with green onions and sesame seeds",
      "Serve hot with steamed rice and kimchi"
    ],
    tip: "Partially freeze the beef before slicing to get incredibly thin slices!",
    servings: 4,
    calories: 380,
    protein: "28g",
    carbs: "12g",
    fat: "24g",
    cuisine: "Korean",
    rating: 4.9,
    ratingCount: 305,
    videoUrl: "",
    allergens: ["soy", "sesame"],
    dietaryInfo: ["dairy-free"]
  },
  {
    id: 27,
    title: "Classic Butter Chicken",
    tags: ["dinner", "indian", "comfort", "main"],
    prepTime: 30,
    cookTime: 30,
    totalTime: 60,
    difficulty: "Medium",
    category: "main",
    description: "Tender chicken cooked in a rich, creamy tomato and butter sauce.",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800",
    ingredients: [
      "1 lb chicken thighs, cubed",
      "1/2 cup plain yogurt",
      "2 tbsp garam masala",
      "1 can tomato puree",
      "1/2 cup heavy cream",
      "3 tbsp butter",
      "1 onion, finely diced",
      "2 cloves garlic and 1 inch ginger, minced"
    ],
    instructions: [
      "Marinate chicken in yogurt and 1 tbsp garam masala for 30 mins",
      "In a deep pan, melt butter and sauté onions until golden",
      "Add garlic, ginger, and remaining spices, cooking until fragrant",
      "Add tomato puree and simmer for 15 minutes",
      "Stir in heavy cream and chicken (with marinade)",
      "Simmer for another 15 minutes until chicken is cooked",
      "Garnish with cilantro and serve with naan"
    ],
    tip: "Use chicken thighs instead of breasts for more tender and flavorful meat!",
    servings: 4,
    calories: 520,
    protein: "28g",
    carbs: "14g",
    fat: "40g",
    cuisine: "Indian",
    rating: 4.8,
    ratingCount: 410,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["gluten-free"]
  },
  {
    id: 28,
    title: "Homemade Sushi Rolls",
    tags: ["dinner", "japanese", "seafood", "main"],
    prepTime: 40,
    cookTime: 20,
    totalTime: 60,
    difficulty: "Medium",
    category: "main",
    description: "Fresh homemade maki rolls with sushi-grade tuna, avocado, and cucumber.",
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800",
    ingredients: [
      "2 cups sushi rice",
      "3 tbsp rice vinegar",
      "Nori seaweed sheets",
      "8 oz sushi-grade tuna, sliced into strips",
      "1 avocado, sliced",
      "1 cucumber, julienned",
      "Soy sauce, wasabi, and pickled ginger for serving"
    ],
    instructions: [
      "Rinse rice until water runs clear, cook according to package",
      "Gently fold rice vinegar into warm rice and let cool",
      "Place nori on a bamboo sushi mat",
      "Spread a thin, even layer of rice over nori, leaving a 1-inch border at top",
      "Arrange tuna, avocado, and cucumber in a line across the bottom third",
      "Roll tightly using the mat, wetting the border to seal",
      "Cut into 6-8 pieces with a sharp, wet knife"
    ],
    tip: "Keep a bowl of water nearby to wet your hands so the rice doesn't stick!",
    servings: 4,
    calories: 320,
    protein: "16g",
    carbs: "54g",
    fat: "5g",
    cuisine: "Japanese",
    rating: 4.7,
    ratingCount: 155,
    videoUrl: "",
    allergens: ["fish", "soy"],
    dietaryInfo: ["dairy-free", "pescatarian"]
  },
  {
    id: 29,
    title: "Iced Matcha Latte",
    tags: ["drink", "morning", "quick", "healthy"],
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "Easy",
    category: "drinks",
    description: "A refreshing, earthy, and lightly sweetened iced green tea latte.",
    image: "https://images.unsplash.com/photo-1536514072410-5019a3c69182?w=800",
    ingredients: [
      "1 tsp ceremonial grade matcha powder",
      "2 oz hot water (not boiling)",
      "1 cup milk of choice (oat or almond work great)",
      "1-2 tsp honey or simple syrup",
      "Ice cubes"
    ],
    instructions: [
      "Sift matcha powder into a small bowl to remove clumps",
      "Add hot water and whisk vigorously in a W-motion until frothy",
      "Fill a glass with ice cubes",
      "Pour milk over ice and stir in sweetener",
      "Gently pour the frothy matcha over the milk",
      "Stir before drinking"
    ],
    tip: "Use a bamboo whisk (chasen) for the best froth and authentic experience!",
    servings: 1,
    calories: 120,
    protein: "4g",
    carbs: "15g",
    fat: "4g",
    cuisine: "Japanese",
    rating: 4.9,
    ratingCount: 200,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 30,
    title: "Classic Tiramisu",
    tags: ["dessert", "italian", "no-bake"],
    prepTime: 30,
    cookTime: 0,
    totalTime: 240,
    difficulty: "Medium",
    category: "dessert",
    description: "An elegant Italian dessert made with espresso-soaked ladyfingers and creamy mascarpone.",
    image: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800",
    ingredients: [
      "1 cup strong espresso, cooled",
      "3 tbsp coffee liqueur (optional)",
      "3 large egg yolks",
      "1/2 cup granulated sugar",
      "8 oz mascarpone cheese, room temp",
      "1 cup heavy whipping cream",
      "1 package ladyfingers (savoiardi)",
      "Cocoa powder for dusting"
    ],
    instructions: [
      "Whisk egg yolks and sugar over a double boiler until pale and thick",
      "Remove from heat and gently fold in the mascarpone cheese",
      "In a separate bowl, whip heavy cream until stiff peaks form, fold into mascarpone mix",
      "Combine espresso and liqueur in a shallow dish",
      "Quickly dip each ladyfinger into espresso and arrange in an 8x8 dish",
      "Spread half the mascarpone mixture over the ladyfingers",
      "Repeat with another layer of dipped ladyfingers and remaining mascarpone",
      "Chill for at least 4 hours, dust with cocoa powder before serving"
    ],
    tip: "Do not soak the ladyfingers too long—just a quick 1-second dip on each side!",
    servings: 8,
    calories: 410,
    protein: "6g",
    carbs: "38g",
    fat: "25g",
    cuisine: "Italian",
    rating: 4.9,
    ratingCount: 350,
    videoUrl: "",
    allergens: ["dairy", "eggs", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 31,
    title: "Fresh Caprese Salad",
    tags: ["salad", "italian", "healthy", "vegetarian"],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "Easy",
    category: "soup-salad",
    description: "A simple, beautiful Italian salad starring ripe tomatoes, fresh mozzarella, and basil.",
    image: "https://images.unsplash.com/photo-1592417817098-8fd3d9eb14a5?w=800",
    ingredients: [
      "3 large ripe tomatoes, sliced 1/4 inch thick",
      "1 lb fresh mozzarella cheese, sliced",
      "1 bunch fresh basil",
      "2 tbsp extra virgin olive oil",
      "1 tbsp balsamic glaze",
      "Coarse sea salt and freshly ground black pepper"
    ],
    instructions: [
      "Alternate layers of tomato and mozzarella slices on a serving platter",
      "Tuck whole basil leaves between the slices",
      "Drizzle generously with extra virgin olive oil",
      "Drizzle lightly with balsamic glaze",
      "Season with coarse salt and freshly ground pepper just before serving"
    ],
    tip: "The quality of the tomatoes and olive oil makes or breaks this dish!",
    servings: 4,
    calories: 280,
    protein: "18g",
    carbs: "8g",
    fat: "22g",
    cuisine: "Italian",
    rating: 4.8,
    ratingCount: 210,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free", "low-carb"]
  },
  {
    id: 32,
    title: "Iced Caramel Macchiato",
    tags: ["drink", "coffee", "quick"],
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "Easy",
    category: "drinks",
    description: "A coffeehouse classic made at home with vanilla syrup, cold milk, espresso, and caramel drizzle.",
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800",
    ingredients: [
      "1 tbsp vanilla syrup",
      "1 cup cold milk",
      "Ice cubes",
      "2 shots espresso (or 1/2 cup strong brewed coffee)",
      "Caramel sauce for drizzling"
    ],
    instructions: [
      "Add vanilla syrup to the bottom of a tall glass",
      "Fill the glass with ice cubes",
      "Pour cold milk over the ice",
      "Slowly pour the espresso over the milk to create a layered effect",
      "Generously drizzle caramel sauce on top",
      "Stir well before drinking"
    ],
    tip: "For the best layered look, pour the espresso over the back of a spoon!",
    servings: 1,
    calories: 210,
    protein: "8g",
    carbs: "32g",
    fat: "5g",
    cuisine: "American",
    rating: 4.6,
    ratingCount: 175,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 33,
    title: "Classic French Onion Soup",
    tags: ["soup", "dinner", "comfort", "french"],
    prepTime: 15,
    cookTime: 60,
    totalTime: 75,
    difficulty: "Medium",
    category: "soup-salad",
    description: "Rich, caramelized onion broth topped with crusty bread and bubbly gruyère cheese.",
    image: "https://images.unsplash.com/photo-1602414777555-5f9f69bf8f8e?w=800",
    ingredients: [
      "4 large yellow onions, sliced",
      "3 tbsp butter",
      "1/2 cup dry white wine",
      "4 cups beef broth",
      "1 tsp fresh thyme",
      "4 slices French baguette, toasted",
      "1 cup grated Gruyère cheese"
    ],
    instructions: [
      "Melt butter in a large pot over medium-low heat",
      "Add onions and cook slowly for 40-45 minutes until deeply caramelized",
      "Deglaze the pot with white wine, scraping up browned bits",
      "Add beef broth and thyme, simmer for 15 minutes",
      "Ladle soup into oven-safe bowls",
      "Top each bowl with a toasted baguette slice and a handful of Gruyère",
      "Broil for 3-5 minutes until cheese is melted and golden"
    ],
    tip: "Patience is key for the onions—don't rush the caramelization process!",
    servings: 4,
    calories: 340,
    protein: "14g",
    carbs: "30g",
    fat: "18g",
    cuisine: "French",
    rating: 4.8,
    ratingCount: 290,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: []
  },
  {
    id: 34,
    title: "Churros with Chocolate Sauce",
    tags: ["dessert", "mexican", "fried", "comfort"],
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    difficulty: "Medium",
    category: "dessert",
    description: "Crispy, cinnamon-sugar coated fried dough served with a rich, warm chocolate dipping sauce.",
    image: "https://images.unsplash.com/photo-1624371414361-e670edf48f8d?w=800",
    ingredients: [
      "1 cup water",
      "2 1/2 tbsp sugar",
      "1/2 tsp salt",
      "2 tbsp vegetable oil",
      "1 cup all-purpose flour",
      "Oil for frying",
      "1/2 cup sugar + 1 tsp cinnamon (for coating)",
      "4 oz dark chocolate + 1/2 cup heavy cream (for dipping)"
    ],
    instructions: [
      "In a saucepan, bring water, 2.5 tbsp sugar, salt, and 2 tbsp oil to a boil",
      "Remove from heat and stir in flour until a ball forms",
      "Heat frying oil to 375°F (190°C) in a deep pot",
      "Pipe 4-inch strips of dough from a piping bag into the hot oil",
      "Fry until golden brown, about 2-3 minutes per side",
      "Drain on paper towels, then immediately roll in cinnamon-sugar",
      "Melt chocolate and heavy cream together for the dipping sauce"
    ],
    tip: "Use a star-shaped piping tip to get the classic churro ridges!",
    servings: 6,
    calories: 410,
    protein: "4g",
    carbs: "48g",
    fat: "22g",
    cuisine: "Mexican",
    rating: 4.8,
    ratingCount: 320,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: ["vegetarian"]
  },
  {
    id: 35,
    title: "Classic Eggs Benedict",
    tags: ["breakfast", "brunch", "comfort"],
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    difficulty: "Medium",
    category: "breakfast",
    description: "Toasted English muffins topped with Canadian bacon, poached eggs, and rich hollandaise.",
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800",
    ingredients: [
      "2 English muffins, split and toasted",
      "4 slices Canadian bacon",
      "4 large eggs",
      "1 tsp white vinegar",
      "3 egg yolks",
      "1 tbsp lemon juice",
      "1/2 cup unsalted butter, melted",
      "Pinch of cayenne pepper"
    ],
    instructions: [
      "In a blender, combine 3 egg yolks, lemon juice, and cayenne. Blend for 5 seconds.",
      "Slowly stream in melted, hot butter while blending until hollandaise is thick",
      "Sear Canadian bacon in a skillet until edges are browned",
      "Poach the 4 eggs in simmering water with a splash of vinegar for 3 minutes",
      "Assemble: English muffin, Canadian bacon, poached egg",
      "Generously spoon hollandaise sauce over the top and garnish with chives"
    ],
    tip: "Using a blender for hollandaise is foolproof and saves your arm from whisking!",
    servings: 2,
    calories: 620,
    protein: "26g",
    carbs: "28g",
    fat: "44g",
    cuisine: "American",
    rating: 4.8,
    ratingCount: 420,
    videoUrl: "",
    allergens: ["eggs", "dairy", "gluten"],
    dietaryInfo: []
  },
  {
    id: 36,
    title: "Tropical Acai Bowl",
    tags: ["breakfast", "healthy", "quick", "vegan"],
    prepTime: 10,
    cookTime: 0,
    totalTime: 10,
    difficulty: "Easy",
    category: "breakfast",
    description: "Thick, refreshing acai puree topped with fresh fruit, granola, and coconut flakes.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    ingredients: [
      "2 frozen acai puree packets",
      "1/2 frozen banana",
      "1/4 cup apple juice or coconut water",
      "1/4 cup granola",
      "Fresh berries (strawberries, blueberries)",
      "Kiwi slices",
      "Shredded coconut and chia seeds"
    ],
    instructions: [
      "Break the frozen acai packets into chunks and add to a blender",
      "Add the frozen banana and a splash of liquid",
      "Blend on high, using a tamper or stopping to scrape down sides, until thick and smooth",
      "Scoop the thick base into a bowl",
      "Arrange granola, fresh berries, kiwi, coconut, and chia seeds on top",
      "Serve immediately with a spoon"
    ],
    tip: "Keep the liquid to a minimum to maintain that perfect thick scoopable texture!",
    servings: 1,
    calories: 380,
    protein: "6g",
    carbs: "72g",
    fat: "10g",
    cuisine: "Brazilian",
    rating: 4.9,
    ratingCount: 230,
    videoUrl: "",
    allergens: ["tree nuts"],
    dietaryInfo: ["vegan", "vegetarian", "dairy-free", "gluten-free"]
  },
  {
    id: 37,
    title: "Mango Lassi",
    tags: ["drink", "indian", "refreshing", "quick"],
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    difficulty: "Easy",
    category: "drinks",
    description: "A creamy, cooling Indian yogurt drink blended with sweet ripe mangoes and a touch of cardamom.",
    image: "https://images.unsplash.com/photo-1626074163473-04e433a0b3ff?w=800",
    ingredients: [
      "1 cup ripe mango chunks (fresh or frozen)",
      "1 cup plain yogurt (whole milk preferred)",
      "1/2 cup milk",
      "2 tbsp honey or sugar",
      "1/4 tsp ground cardamom",
      "Ice cubes"
    ],
    instructions: [
      "Add mango, yogurt, milk, sugar, and cardamom to a blender",
      "Blend until completely smooth and creamy",
      "If the consistency is too thick, add a little more milk",
      "Add a handful of ice cubes and blend for another 10 seconds",
      "Pour into glasses and garnish with a sprinkle of cardamom or saffron"
    ],
    tip: "Use Alphonso mangoes if you can find them for the most authentic flavor!",
    servings: 2,
    calories: 220,
    protein: "8g",
    carbs: "38g",
    fat: "5g",
    cuisine: "Indian",
    rating: 4.8,
    ratingCount: 160,
    videoUrl: "",
    allergens: ["dairy"],
    dietaryInfo: ["vegetarian", "gluten-free"]
  },
  {
    id: 38,
    title: "Authentic Pad Thai",
    tags: ["dinner", "thai", "noodles", "quick"],
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    difficulty: "Medium",
    category: "main",
    description: "Stir-fried rice noodles with a sweet and tangy tamarind sauce, shrimp, peanuts, and lime.",
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800",
    ingredients: [
      "8 oz flat rice noodles",
      "3 tbsp tamarind paste",
      "2 tbsp fish sauce",
      "2 tbsp palm sugar",
      "1/2 lb shrimp, peeled and deveined",
      "2 eggs, lightly beaten",
      "1 cup bean sprouts",
      "1/4 cup crushed roasted peanuts, plus lime wedges"
    ],
    instructions: [
      "Soak rice noodles in warm water for 30 minutes until pliable, drain",
      "Mix tamarind, fish sauce, and palm sugar in a small bowl",
      "Heat oil in a wok over high heat, cook shrimp until pink, remove",
      "Add eggs to the wok and scramble quickly",
      "Add noodles and sauce, tossing vigorously until noodles are soft",
      "Return shrimp to the wok along with bean sprouts, toss for 1 minute",
      "Serve hot, garnished with crushed peanuts and lime wedges"
    ],
    tip: "Don't over-soak the noodles—they should still have a little bite before cooking!",
    servings: 3,
    calories: 450,
    protein: "22g",
    carbs: "65g",
    fat: "14g",
    cuisine: "Thai",
    rating: 4.7,
    ratingCount: 390,
    videoUrl: "",
    allergens: ["shellfish", "fish", "eggs", "peanuts"],
    dietaryInfo: ["dairy-free", "gluten-free"]
  },
  {
    id: 39,
    title: "Greek Gyros with Tzatziki",
    tags: ["dinner", "greek", "comfort", "main"],
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    difficulty: "Medium",
    category: "main",
    description: "Spiced chicken or lamb wrapped in warm pita bread with fresh veggies and cooling tzatziki sauce.",
    image: "https://images.unsplash.com/photo-1528735000313-039ec3a473b0?w=800",
    ingredients: [
      "1 lb chicken thighs, sliced",
      "2 tbsp olive oil, lemon juice, oregano, and garlic for marinade",
      "4 soft pita breads",
      "1 cup tzatziki sauce",
      "1 tomato, diced",
      "1/2 red onion, thinly sliced",
      "Kalamata olives and feta cheese (optional)"
    ],
    instructions: [
      "Marinate chicken in olive oil, lemon juice, garlic, and oregano for 30 mins",
      "Cook chicken in a skillet over medium-high heat until deeply browned",
      "Warm the pita breads in a dry skillet or oven",
      "Spread a generous layer of tzatziki on each warm pita",
      "Add the cooked chicken, tomato, and red onion",
      "Fold the pita in half like a taco to serve"
    ],
    tip: "A pinch of smoked paprika in the marinade gives a great grilled flavor indoors!",
    servings: 4,
    calories: 520,
    protein: "32g",
    carbs: "45g",
    fat: "22g",
    cuisine: "Greek",
    rating: 4.8,
    ratingCount: 260,
    videoUrl: "",
    allergens: ["dairy", "gluten"],
    dietaryInfo: []
  },
  {
    id: 40,
    title: "Spicy Shakshuka",
    tags: ["breakfast", "brunch", "middle eastern", "healthy"],
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    difficulty: "Easy",
    category: "main",
    description: "Eggs gently poached in a rich, spiced tomato and bell pepper sauce. Perfect with crusty bread.",
    image: "https://images.unsplash.com/photo-1590165482129-1b8b27698780?w=800",
    ingredients: [
      "1 tbsp olive oil",
      "1 medium onion, diced",
      "1 red bell pepper, diced",
      "3 cloves garlic, minced",
      "1 tsp cumin, 1 tsp paprika, 1/4 tsp chili flakes",
      "1 can (28 oz) crushed tomatoes",
      "4-6 large eggs",
      "Fresh cilantro or parsley and crusty bread"
    ],
    instructions: [
      "Heat olive oil in a large skillet. Sauté onion and bell pepper until soft",
      "Add garlic and spices, cooking for 1 minute until fragrant",
      "Pour in crushed tomatoes, season with salt/pepper, simmer for 10-15 minutes",
      "Make small wells in the sauce using a spoon",
      "Crack an egg into each well",
      "Cover the skillet and cook for 5-8 minutes until egg whites are set",
      "Garnish with fresh herbs and serve hot with crusty bread"
    ],
    tip: "Keep the yolks runny for the perfect dipping sauce for your bread!",
    servings: 3,
    calories: 280,
    protein: "14g",
    carbs: "24g",
    fat: "15g",
    cuisine: "Middle Eastern",
    rating: 4.9,
    ratingCount: 310,
    videoUrl: "",
    allergens: ["eggs"],
    dietaryInfo: ["vegetarian", "dairy-free", "gluten-free"]
  }
];

if (typeof window !== 'undefined') {
  window.recipes = recipes;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = recipes;
}
